services:
  open-webui:
    build:
      context: https://github.com/GaryTseng-SSSTC/open-webui.git#main
      dockerfile: Dockerfile
    #image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - D:/open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY=899BYHkySz6zCvQ/DbCYltzk8oC4fljAZgfOMsLFMquDZvtyq5ipRHzeedpdo9+l'
      - 'DEPLOYMENT_ID=${DEPLOYMENT_ID-}'
      #- WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-User-Email
      #- WEBUI_AUTH_TRUSTED_NAME_HEADER=X-User-Name
      #- ENABLE_LOGIN_FORM=false
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
